import { useState } from "react";
import Head from "next/head";
import type { NextPage } from "next";
import { Status } from "~~/components/Status";

const Challengepage: NextPage = () => {
  const [approvalLoading, setApprovalLoading] = useState(false);
  const [tokenValue, setTokenValue] = useState("");
  return (
    <>
      <Head>
        <title>Challengepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="flex items-center flex-col flex-grow pt-10">
        <div className="px-5">
          <h1 className="text-center mb-8">
            <span className="block text-4xl font-bold">Challenge this task!</span>
          </h1>
        </div>
        <div className="card w-120 bg-base-100 shadow-xl mb-10">
          <div className="card-body">
            <div className="flex justify-between items-center">
              <h2 className="card-title mb-0 mr-10">Task1</h2>
              <Status speed="0.5eth/min" amount="1.5" />
            </div>
            <p>description description description</p>
          </div>
        </div>

        <div className="flex  items-center border-2 border-primary rounded-lg mb-5">
          <input
            value={tokenValue}
            onChange={e => setTokenValue(e.target.value)}
            type="text"
            placeholder="0.00"
            className="input input-ghost pl-1 focus:outline-none focus:bg-transparent focus:text-gray-400 h-[2.2rem] min-h-[2.2rem] border w-full font-medium placeholder:text-accent/50 text-gray-400 grow "
          />
        </div>
        <button
          className={`btn btn-primary ${approvalLoading ? "loading" : ""}`}
          disabled={approvalLoading}
          onClick={async () => {
            ("");
          }}
        >
          Deposit tokens to chanllenge
        </button>
      </div>
    </>
  );
};

export default Challengepage;
