import { useContext, useState } from "react";
import Head from "next/head";
import { TaskContext } from "./TaskContext";
// import Link from "next/link";
import type { NextPage } from "next";

// import { useSigner } from "wagmi";
// import { Status } from "~~/components/Status";

interface Task {
  id?: number;
  title: string;
  description?: string;
  speed: string;
  amount?: string;
}

const Create: NextPage = () => {
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [speed, setSpeed] = useState("");
  const [task, setTask] = useState<Task>();
  const [createLoading, setCreateLoading] = useState(false);
  // const { data: signer } = useSigner();
  const tasks = useContext(TaskContext);

  const handleCreate = async () => {
    setCreateLoading(true);
    setTask({
      title: name,
      description: description,
      speed: speed,
    });
    await tasks?.addTask(task as Task);
    setCreateLoading(false);
  };
  return (
    <>
      <Head>
        <title>Create</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex items-center flex-col flex-grow pt-10">
        <div className="px-5">
          <h1 className="text-center mb-8">
            <span className="block text-4xl font-bold">Create your first task now!</span>
          </h1>
        </div>
        <div className="flex flex-col space-y-5">
          <div className="flex w-full items-center border-2 border-primary rounded-lg">
            <input
              value={name}
              onChange={e => setName(e.target.value)}
              type="text"
              placeholder="Name"
              className="input input-ghost pl-1 focus:outline-none focus:bg-transparent focus:text-gray-400 h-[2.2rem] min-h-[2.2rem] border w-full font-medium placeholder:text-accent/50 text-gray-400 grow"
            />
          </div>
          <div className="flex w-full items-center border-2 border-primary rounded-lg">
            <input
              value={description}
              onChange={e => setDescription(e.target.value)}
              type="text"
              placeholder="Description"
              className="input input-ghost pl-1 focus:outline-none focus:bg-transparent focus:text-gray-400 h-[2.2rem] min-h-[2.2rem] border w-full font-medium placeholder:text-accent/50 text-gray-400 grow"
            />
          </div>
          <input type="file" className="file-input w-full max-w-xs" />
          <button
            className={`btn btn-primary ${createLoading ? "loading" : ""}`}
            disabled={createLoading}
            onClick={async () => {
              await handleCreate();
            }}
          >
            Create
          </button>
        </div>
      </div>
    </>
  );
};

export default Create;
