import Head from "next/head";
import type { NextPage } from "next";

const Userpage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Userpage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className="flex items-center flex-col flex-grow pt-10">
        <div className="px-5">
          <h1 className="text-center mb-8">
            <span className="block text-4xl font-bold">Vitalik Buterin</span>
          </h1>
        </div>
        <div className="flex flex-col space-y-2">
          <div className="card w-96 bg-base-100 shadow-xl">
            <div className="card-body">
              <h2 className="card-title">Task1</h2>
              <p>description description description</p>
              <div className="card-actions justify-end">
                <button className="btn btn-primary">Challenge</button>
              </div>
            </div>
          </div>
          <div className="card w-96 bg-base-100 shadow-xl">
            <div className="card-body">
              <h2 className="card-title">Task2</h2>
              <p>description description description</p>
              <div className="card-actions justify-end">
                <button className="btn btn-primary">Challenge</button>
              </div>
            </div>
          </div>
          <div className="card w-96 bg-base-100 shadow-xl">
            <div className="card-body">
              <h2 className="card-title">Task3</h2>
              <p>description description description</p>
              <div className="card-actions justify-end">
                <button className="btn btn-primary">Challenge</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Userpage;
